import classNames from 'classnames';
import Head from 'next/head';
import Image from 'next/image';
import Typewriter from '../components/Typewrite';
import styles from '../styles/Home.module.scss';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spencer Strelsov</title>
        <meta name="Personal website" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Image src="/website_profile_pic.jpg" alt="Photo of Spencer" height={255} width={200} /> */}
        <div className={styles.typewriter}>
          <h1 className={classNames(styles.title, styles['typewriter-title'])}>
            <Typewriter
              addedPhrases={[
                "Hey, I'm Spencer!",
                "I'm a senior at Yale.",
                "I'm from Louisville.",
                "I'm passionate about"
              ]}
              loopedPhrases={['technology', 'startups', 'history', 'law']}
              loopNewLine={true}
            />
          </h1>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          Copyright{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </p>
      </footer>
    </div>
  );
};

export default Home;
